# Problem 2: Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

sum_even_fibonacci <- function(n){
    result <- integer(n)
    result[1] <- 1
    result[2] <- 2
    i <- 3
    while(result[i-1]<n){
        result[i] <- result[i-1] + result[i-2]
        i <- i+1
    }
    sum(result[result %% 2 == 0])
}

# Result:
# > sum_even_fibonacci(4000000)
# [1] 4613732
